language: node_js
node_js:
  - lts/*

services:
  - docker

cache: yarn

# before_install:

script:
  - docker build -t m00nwatcher/jackett-sync .

deploy:
  - provider: npm
    email: "lmarianski@protonmail.com"
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
    tag: next
  - provider: script
    script: bash docker_push
    on:
      tags: true